[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
